# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Not Decided
tagline:          'Right now a blog'
description:      'As it must be obvious from the domain name, that Mihir has not decided what to do with the domain name. So right now it points to what Mihir believes is a blog.'
url:              http://notdecided.com

author:
  name:           'Mihir'
  url:            https://twitter.com/mihirk

paginate:         5

# Custom vars

github:
  repo:           https://github.com/mihirk